### ISSUE TITLE
Add unique ID to activity

### ISSUE THREAD

**Issue by magska** [schibsted/sdk-js-event-tracking#23]
There should be an unique ID generated client side for each activity. UUIDv4 should be used. Need to define where in the activity it should go (context?)

**Comment by voldern** [comment]
In our engage js sdk we use https://www.npmjs.com/package/uuid which works in most browsers. There are also several more implementations up on NPM: https://www.npmjs.com/search?q=uuid

**Comment by sundsdal** [comment]
How does this match the requirement of not including external libraries? And what is the field name?

**Comment by magska** [comment]
@sundsdal it doesn't use any external libraries. The field is '@id' in the root of the activity.

**Comment by sundsdal** [comment]
Ah yes, just saw the code. having trouble keeping up.
